
Vagrant.configure(2) do |config|

  config.vm.box = "centos/6"

  config.vm.provision "shell", path: "install.sh"

  config.vm.synced_folder "../../scripts", "/opt/scripts"
  config.vm.synced_folder "../../test", "/var/www/html/test"

  config.vm.network "private_network", ip: "192.168.22.25"


  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.provider "virtualbox" do |v|
    v.name = "wowtest_vm"
  end

end
